# Generated by Django 6.0.3 on 2026-03-23 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_inquiry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'ordering': ['-created_at']},
        ),
    ]
