# Generated by Django 6.0.3 on 2026-03-20 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_code', models.CharField(max_length=20, unique=True)),
                ('unit_type', models.CharField(blank=True, max_length=50)),
                ('capacity', models.IntegerField(default=1)),
                ('occupancy', models.IntegerField(default=0)),
                ('room_size', models.CharField(blank=True, max_length=50, null=True)),
                ('furnish', models.CharField(blank=True, max_length=100, null=True)),
                ('restroom', models.CharField(blank=True, max_length=50, null=True)),
                ('curfew', models.CharField(blank=True, max_length=50, null=True)),
                ('monthly_rent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(default='Available', max_length=20)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.building')),
            ],
        ),
    ]
